# SPDX-FileCopyrightText: 2023 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

# Accepted licesnes by default
accepted = ["Apache-2.0", "MIT", "Zlib"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-pc-windows-gnullvm",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "i686-pc-windows-gnu",
  "i686-unknown-linux-gnu",
  "i686-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-gnu",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]

# Do not ignore any dependencies
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false

# Try to resolve any time clearlydefined.io marks something as NOASSERTION
filter-noassertion = true

# Specify the license from the github page:
# BSD 3-Clause: https://github.com/phsym/prettytable-rs/blob/master/LICENSE.txt
[prettytable-rs]
  accepted = ["BSD-3-Clause"]

# Specify the triple license for `unicode-ident`
# MIT: https://github.com/dtolnay/unicode-ident/LICENSE-MIT
# Apache-2.0: https://github.com/dtolnay/unicode-ident/LICENSE-APACHE
# Unicode-DFS-2016: https://github.com/dtolnay/unicode-ident/LICENSE-UNICODE
[unicode-ident]
  accepted = ["Unicode-3.0", "Unicode-DFS-2016"]
