# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "clippy"
summary = true
wrap = true

[jobs.check]
  command = ["cargo", "check", "--color", "always"]
  need_stdout = false

[jobs.check-all]
  command = ["cargo", "check", "--all-targets", "--color", "always"]
  need_stdout = false

[jobs.clippy]
  apply_gitignore = false
  command = [
    "cargo",
    "+nightly",
    "clippy",
    "--color",
    "always",
    "--",
    "-W",
    "clippy::pedantic",
    "-W",
    "clippy::nursery",
    "-W",
    "clippy::unwrap_used",
    "-W",
    "clippy::expect_used",
  ]
  need_stdout = false

[jobs.test]
  command = [
    "cargo",
    "test",
    "--",
    "--color",
    "always",  # https://github.com/Canop/bacon/issues/124
  ]
  need_stdout = true

[jobs.doc]
  command = ["cargo", "doc", "--color", "always", "--no-deps"]
  need_stdout = false
  on_success = "back"

[jobs.doc-open]
  command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
  need_stdout = false
  on_success = "back"

[jobs.audit]
  command = ["cargo", "audit", "--color", "always"]
  need_stdout = true

[keybindings]
  a = "job:audit"
  c = "job:clippy"
  ctrl-c = "job:check-all"
  d = "job:doc"
  o = "job:doc-open"
  t = "job:test"
