# SPDX-FileCopyrightText: 2023 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

# This template contains all of the possible sections and their default values

# Note that all fields that take a lint level have these possible values:
# * deny - An error will be produced and the check will fail
# * warn - A warning will be produced, but the check will not fail
# * allow - No warning or error will be produced, though in some cases a note
# will be

# The values provided in this template are the default values that will be used
# when any section or field is not specified in your own configuration

[graph]
  # Root options
  targets = [
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-musl" },
    { triple = "i686-pc-windows-gnu" },
    { triple = "i686-unknown-linux-gnu" },
    { triple = "i686-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
  ]
  # When creating the dependency graph used as the source of truth when checks are
  # executed, this field can be used to prune crates from the graph, removing them
  # from the view of cargo-deny.
  #exclude = []

  # If true, metadata will be collected with `--all-features`.
  all-features = true

  # If set, these feature will be enabled when collecting metadata.
  #features = []

[advisories]
  # The path where the advisory database is cloned/fetched into
  db-path = "~/.cargo/advisory-db"

  # The url(s) of the advisory databases to use
  db-urls = ["https://github.com/rustsec/advisory-db"]

  # The lint level for unmaintained crates
  unmaintained = "workspace"

  # The lint level for crates that have been yanked from their source registry
  yanked = "warn"

  # A list of advisory IDs to ignore. Note that ignored advisories will still
  # output a note when they are encountered.
  ignore = [
    #"RUSTSEC-0000-0000",
  ]

# This section is considered when running `cargo deny check licenses`
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
  allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
  ]

  # The confidence threshold for detecting a license from license text.
  # [possible values: any between 0.0 and 1.0].
  confidence-threshold = 0.8

  # Allow 1 or more licenses on a per-crate basis, so that particular licenses
  # aren't accepted for every possible crate as with the normal allow list
  exceptions = [
    #{ allow = ["Zlib"], name = "adler32", version = "*" },
  ]

  # Some crates don't have (easily) machine readable licensing information,
  # adding a clarification entry for it allows you to manually specify the
  # licensing information
  #[[licenses.clarify]]
  # The name of the crate the clarification applies to
  #name = "ring"
  # The optional version constraint for the crate
  #version = "*"
  # The SPDX expression for the license requirements of the crate
  #expression = "MIT AND ISC AND OpenSSL"
  # One or more files in the crate's source used as the "source of truth" for
  # the license expression. If the contents match, the clarification will be used
  # when running the license check, otherwise the clarification will be ignored
  # and the crate will be checked normally, which may produce warnings or errors
  # depending on the rest of your configuration
  #license-files = [
  # Each entry is a crate relative path, and the (opaque) hash of its contents
  #{ path = "LICENSE", hash = 0xbd0eed23 }
  #]

  [licenses.private]
    # If true, ignores workspace crates that aren't published, or are only
    # published to private registries.
    # To see how to mark a crate as unpublished (to the official registry),
    # visit https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field.
    ignore = false
    # One or more private registries that you might publish crates to, if a crate
    # is only published to private registries, and ignore is true, the crate will
    # not have its license(s) checked
    registries = [
      #"https://sekretz.com/registry
    ]

# This section is considered when running `cargo deny check bans`.
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
  # Lint level for when multiple versions of the same crate are detected
  multiple-versions = "warn"

  # Lint level for when a crate version requirement is `*`
  wildcards = "allow"

  # The graph highlighting used when creating dotgraphs for crates
  # with multiple versions
  highlight = "all"

  # The default lint level for `default` features for crates that are members of
  # the workspace that is being checked. This can be overridden by allowing/denying
  # `default` on a crate-by-crate basis if desired.
  workspace-default-features = "allow"

  # The default lint level for `default` features for external crates that are not
  # members of the workspace. This can be overridden by allowing/denying `default`
  # on a crate-by-crate basis if desired.
  external-default-features = "allow"

  # List of crates that are allowed. Use with care!
  allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
  ]

  # List of crates to deny
  deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ name = "ansi_term", version = "=0.11.0" },
    #
    # Wrapper crates can optionally be specified to allow the crate when it
    # is a direct dependency of the otherwise banned crate
    #{ name = "ansi_term", version = "=0.11.0", wrappers = [] },
  ]

  # List of features to allow/deny
  # Each entry the name of a crate and a version range. If version is
  # not specified, all versions will be matched.
  #[[bans.features]]
  #name = "reqwest"
  # Features to not allow
  #deny = ["json"]
  # Features to allow
  #allow = [
  #    "rustls",
  #    "__rustls",
  #    "__tls",
  #    "hyper-rustls",
  #    "rustls",
  #    "rustls-pemfile",
  #    "rustls-tls-webpki-roots",
  #    "tokio-rustls",
  #    "webpki-roots",
  #]
  # If true, the allowed features must exactly match the enabled feature set. If
  # this is set there is no point setting `deny`
  #exact = true

  # Certain crates/versions that will be skipped when doing duplicate detection.
  skip = [{ name = "itertools", version = "0.13.0" }]
  # Similarly to `skip` allows you to skip certain crates during duplicate
  # detection. Unlike skip, it also includes the entire tree of transitive
  # dependencies starting at the specified crate, up to a certain depth, which is
  # by default infinite.
  skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
  ]

[sources]
  # Lint level for what to happen when a crate from a crate registry that is not
  # in the allow list is encountered
  unknown-registry = "warn"
  # Lint level for what to happen when a crate from a git repository that is not
  # in the allow list is encountered
  unknown-git = "warn"
  # List of URLs for allowed crate registries. Defaults to the crates.io index
  # if not specified. If it is specified but empty, no registries are allowed.
  allow-registry = ["https://github.com/rust-lang/crates.io-index"]
  # List of URLs for allowed Git repositories
  allow-git = []

  [sources.allow-org]
    # 1 or more github.com organizations to allow git sources for
    # github = ["AliSajid", "CogDisResLab"]

[output]
  feature-depth = 2
