# SPDX-FileCopyrightText: 2023 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
  SPDX-FileCopyrightText = "2023 - 2026 Ali Sajid Imami"
  SPDX-License-Identifier = "CC0-1.0"
  path = [
    ".gitignore",
    ".gitleaks_baseline.json",
    ".gitleaksignore",
    ".markdownlintignore",
    ".secrets.baseline",
    ".vscode/*",
    "guide/.gitignore",
  ]
  precedence = "override"

[[annotations]]
  SPDX-FileCopyrightText = "2023 - 2026 Ali Sajid Imami"
  SPDX-License-Identifier = "MIT OR Apache-2.0"
  path = "Cargo.lock"
  precedence = "override"

[[annotations]]
  SPDX-FileCopyrightText = "2023 - 2026 Ali Sajid Imami"
  SPDX-License-Identifier = "CC0-1.0"
  path = [
    ".markdownlint.json",
    "CHANGELOG.md",
    "licenses_report.json",
    "licenses_report.md",
    "meta/vale-styles/config/vocabularies/Custom/*.txt",
    "renovate.json",
  ]
  precedence = "override"

[[annotations]]
  SPDX-FileCopyrightText = "2023 - 2026 Ali Sajid Imami"
  SPDX-License-Identifier = "MIT OR Apache-2.0"
  path = [
    "guide/src/mdbook-plantuml-img/*.svg",
    "lang/grammar.ebnf",
    "lang/railroad/*.svg",
  ]
  precedence = "override"
