[toolchain]
channel = "nightly-2023-12-22"
components = [ "rustfmt", "rustc", "cargo", "clippy", "rust-std", "rust-docs"]
targets = [ "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc" ]
profile = "default"
