# SPDX-FileCopyrightText: 2023 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

[formatting]
  indent_entries = true
  indent_tables = true


[[rule]]
  include = ["**/Cargo.toml"]
  keys = ["dependencies", "dev-dependencies"]

  [rule.formatting]
    reorder_keys = true

[[rule]]
  include = [
    "REUSE.toml",
    "about.toml",
    "deny.toml",
    "mise.toml",
    "nextest.toml",
    "taplo.toml",
  ]

  [rule.formatting]
    reorder_arrays = true
    reorder_keys = true

[[rule]]
  include = ["bacon.toml"]

  [rule.formatting]
    reorder_arrays = false
    reorder_keys = true
