# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        branches:
            - "*"
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:
jobs:
    security_audit:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
            - name: Install Rust
              uses: dtolnay/rust-toolchain@89b12181fb390509a0842a86cc55eeb8eb928c1d # stable
            - name: Install cargo-audit
              uses: taiki-e/install-action@861a07ce7084f55488e375df125cdc99bba60eb7 # v2.87.23
              with:
                tool: cargo-audit
            - name: Security Audit
              run: cargo audit
